### ISSUE TITLE
Macro to differentiate function symbolically

### ISSUE THREAD

**Issue by Luapulu** [JuliaMath/Calculus.jl#149]
Given a function that is simple enough, I'd like to be able to differentiate an existing function symbolically, by simply putting a macro in front of it. It could work something like this:

```julia
cubefunc_diff = @differentiate function cubefunc(x)
    return x * x * x
end

# cubefunc_diff(3) would return derivative evaluated at 3
```

I've started trying to implement this myself, but I'm not sure how best to proceed or if what I'm proposing is even a good idea. Would this be a good idea?

**Comment by johnmyleswhite** [comment]
I always wanted this, but don't do anything to maintain this repo anymore. Not clear to me where the future for symbolic differentiation is, but probably not here. Also worth noting that people usually would discourage differentiation for serious work since the simplification steps are seldom good enough to provide optimal code relative to automatic differentiation.

**Comment by Luapulu** [comment]
Interesting, I think trying to implement this might be a hobby project of mine in the future.
